name: REPACRR
seed: 42
gpu_device: null

metric: ERR20

batch_size: 32
epochs: 200

sim_matrix_config:
  matrices_path:
    topic: DATA/corpora/cosine/topic_doc_mat
    description: DATA/corpora/cosine/desc_doc_mat
  max_doc_len: 800
  max_query_len: 16
  pos_method: firstk
  use_context: False
  ngrams:  # query_window_size x doc_windows_size (square only allowed)
    - 1
    - 2
    - 3

query_idf_config:
  max_query_len: 16
  idf_vectors_path:
    topic: DATA/corpora/cosine/query_idf/topic_term_idf/
    description: DATA/corpora/cosine/query_idf/desc_term_idf/

use_description: True
use_topic: True

permute: False
num_negative: 6
filter_size: 32
top_k: 3
combine: 16

# Regularization
l2_lambda: 0.001
keep_prob: 0.5

xfilters: null
cascade: null

plot_model: True

nr_samples: 4096
construct_vocab: False

