name: REPACRR
seed: 42
gpu_device: null

metric: ERR20

batch_size: 32
epochs: 50

sim_matrix_config:
  use_static_matrices: False
  matrix_build_mode: 0
  use_masking: False
  matrices_path:
    topic: DATA/corpora/sim_matrices/topic
    description: DATA/corpora/sim_matrices/description
  use_context: False
  context_window: 4
  context_path: 
    topic_description: DATA/corpora/sim_matrices/context_vectors
  max_doc_len: 800
  max_query_len: 16
  pos_method: firstk
  use_maxpooling: True
  ngrams:  # query_window_size x doc_windows_size (square only allowed)
    - 1
    - 2
    - 3

query_idf_config:
  use_query_idf: False
  max_query_len: 16
  idf_vectors_path:
    topic: DATA/corpora/query_idf/topic
    description: DATA/corpora/query_idf/description

use_description: True
use_topic: True

use_convs: True
custom_loss: True
permute: False
num_negative: 6
filter_size: 32
top_k: 3
combine: 16

# Regularization
l2_lambda: 0.01
drop_rate: 0.35
batch_norm: False

nr_samples: 4096

# Retrain
retrain: False
retrain_weight: 3.0
retrain_mode: 1

xfilters: null
cascade: null

plot_model: True
