name: REPACRR
seed: 42
gpu_device: null

metric: ERR20

batch_size: 32
epochs: 2

sim_matrix_config:
  matrices_path:
    description: DATA/corpora/sim_matrices/description
  max_doc_len: 800
  max_query_len: 16
  pos_method: firstk
  use_context: False
  ngrams:  # query_window_size x doc_windows_size (square only allowed)
    - 1
    - 2
    - 3

query_idf_config:
  max_query_len: 16
  idf_vectors_path:
    description: DATA/corpora/query_idf/description

use_description: True
use_topic: False

permute: True
num_negative: 6
filter_size: 32
top_k: 3
combine: 16

# Regularization
l2_lambda: 0.001
keep_prob: 0.5

xfilters: null
cascade: 25.50.75.100

plot_model: True

construct_vocab: False
